# Generated by Django 2.2.13 on 2020-06-13 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockTrading', '0002_auto_20200611_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myWallets', to='StockTrading.Stock'),
        ),
    ]
