# Generated by Django 2.2.13 on 2020-06-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockTrading', '0003_auto_20200613_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywallet',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walletstock', to='StockTrading.Stock'),
        ),
    ]
