# Generated by Django 2.2.13 on 2020-06-13 21:09

import StockTrading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockTrading', '0006_auto_20200613_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[StockTrading.models.validator]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[StockTrading.models.validator]),
        ),
    ]
